### ISSUE TITLE
Statistics of the day/week/month

### ISSUE THREAD

**Issue by hubr64** [nibi79/worxlandroid#9]
Currently, the binding provide three statitistics :
- Total operating time
- Total blade time
- Total distance

An enhancement should be to provide these 3 informations for the current day, for the current week and for the current month. I implement this in a rule but if the binding can provide it natively it would be very nice !

**Comment by nibi79** [comment]
The binding itself is not be able to provide this data because the binding is stateless and don't store any data. After restarting, reloading, editing your configuration etc. all data is lost for the binding.
You need a database to store the values. So the binding is not suitable and your rules (persistence,...) are the right way to do this.
